# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Discord

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  noti:
    runs-on: ubuntu-latest
    steps:
    - name: Notify Discord
      uses: discord-actions/message@v2
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
        message: "Hello, from Github"
    - name: Discord Commits
      uses: Sniddl/discord-commits@v1.6
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        template: "avatar-with-link"
        include-extras: true
